const tipos = {
  modelo: "Marca / Modelo",
  fonte: "Fonte",
  poe: "PoE",
  mac: "Endereço MAC",
  ssid: "SSID",
  ip: "Endereço IP",
  btu: "BTUs",
  ram: "Memória RAM",
  armazenamento: "Armazenamento",
  numeros: "Números Conectados",
  local: " Local",
  "sistema-operacional": "Sistema Operacional",
  processador: "Processador",
  "placa-mae": "Placa Mãe",
  "placa-video": "Placa de Vídeo",
  tipo: "Tipo",
  vesa: "Padrão VESA",
  entradas: "Entradas de Vídeo",
  resolucao: "Resolução",
  potencia: "Potência",
  "tensao-entrada": "Tensão de Entrada",
  "tensao-saida": "Tensão de Saída",
  "tensao-bateria": "Tensão da Bateria",
  setores: "Setores Alimentados",
  tela: "Tamanho da Tela",
  fibra: "Fibra",
  gerenciavel: "Gerenciável",
  portas: "Número de Portas",
};

export default tipos;
